Repository jrsteensen/OpenHornet-Software, pull requests merged in 2024-02, with the labels that each got.

#16 Latest Develop to Master
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  README.md
  docs/SoftwareManual.md
  embedded/OH1_Upper_Instrument_Panel/1A2-MASTER_ARM_PANEL/1A2-MASTER_ARM_PANEL.ino
  embedded/OH1_Upper_Instrument_Panel/1A2-MASTER_ARM_PANEL/Makefile
  embedded/templates/OHSketchTemplate/OHSketchTemplate.ino
Labels: Type: Documentation

#22 Updated doxygen and fixed files to display appropriately.
  docs/Doxyfile
  embedded/OH1_Upper_Instrument_Panel/1A2-MASTER_ARM_PANEL/1A2-MASTER_ARM_PANEL.ino
  embedded/templates/OHSketchTemplate/OHSketchTemplate.ino
Labels: Type: Maintenance, Type: Documentation

#23 Deleting erroneous files.
  embedded/1A2-MASTER_ARM_PANEL/1A2-MASTER_ARM_PANEL.ino
  embedded/1A2-MASTER_ARM_PANEL/Makefile
Labels: Type: Maintenance

#26 Develop
  .github/workflows/bulk-issue-creator.yml
  config/data.csv
  config/template.md.mustache
  docs/SoftwareManual.md
Labels: Type: Maintenance, Type: Documentation

#63 New Spin Rcvy Sketch (#61)
  .github/workflows/ci.yaml
  embedded/OH1_Upper_Instrument_Panel/1A6-SPIN_RCVY_PANEL/1A6-SPIN_RCVY_PANEL.ino
  embedded/OH1_Upper_Instrument_Panel/1A6-SPIN_RCVY_PANEL/Makefile
Labels: Type: Enhancement, Category: Embedded

#62 [NEW SKETCH]: 4A2A1-LDG_GEAR_PANEL.ino
  embedded/OH4_Left_Console/4A2A1-LDG_GEAR_PANEL/4A2A1-LDG_GEAR_PANEL.ino
  embedded/OH4_Left_Console/4A2A1-LDG_GEAR_PANEL/Makefile
Labels: Type: Enhancement, Category: Embedded

#65 Refactor 1A6-SPIN_RCVY_PANEL
  embedded/OH1_Upper_Instrument_Panel/1A6-SPIN_RCVY_PANEL/1A6-SPIN_RCVY_PANEL.ino
Labels: Type: Maintenance, Category: Embedded
